{
    'name':'Student Managemnet',
    'version':'19.0.1.0.0',
    # 'summary':'#',
    # 'description':'#',
    # 'category':'#',
    'auhtor':'Pyae Sone',
    'license': 'LGPL-3',
    'auto_install':False,
    'application':True,
    'installable':True,
    'depends':['base'],
    'data':[
        'security/ir.model.access.csv',
        'views/student_views.xml',
        'views/student_information_view.xml',
        'views/school_class_view.xml',
        'views/school_subject_view.xml',
        'views/school_teacher_view.xml',
        'views/student_menu.xml',
    ],
    'sequence':1,
}